kind: Secret
apiVersion: v1
metadata:
  name: {{ template "pbastia.name" . }}-secret
  labels:
{{ include "pbastia.labels" . | indent 4 }}
  annotations:
    description: A Secret
stringData:
  ghHandle: {{ .Values.ghHandle }}
  moreData: "some static data"
